# Generated by Django 5.2.8 on 2025-11-07 20:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_am',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_bn',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_es',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_hi',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ka',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_pt',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_sq',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_uk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ur',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_zh_hans',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_am',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_bn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_hi',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ka',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_pt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ro',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sq',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ur',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_zh_hans',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_am',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_am',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_ar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_bn',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_es',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_hi',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_ka',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_pt',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_ro',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_sq',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_uk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_ur',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='complementarymaterial',
            name='body_zh_hans',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
