# Generated by Django 5.2.8 on 2025-11-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_body_am_article_body_ar_article_body_bn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_am',
        ),
        migrations.RemoveField(
            model_name='article',
            name='body_ka',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_am',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ka',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_am',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ka',
        ),
        migrations.RemoveField(
            model_name='complementarymaterial',
            name='body_am',
        ),
        migrations.RemoveField(
            model_name='complementarymaterial',
            name='body_ka',
        ),
    ]
