# Generated by Django 5.2.8 on 2025-11-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_socialnetwork_homeconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_image',
            field=models.ImageField(default=None, upload_to='categories/hero/'),
            preserve_default=False,
        ),
    ]
